# Generated by Django 5.0.6 on 2024-05-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentphoto',
            options={'verbose_name': 'Фото детали', 'verbose_name_plural': 'Фото детали'},
        ),
        migrations.AlterField(
            model_name='componentphoto',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.component', verbose_name='Деталь'),
        ),
    ]
