# Generated by Django 5.0.6 on 2024-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_componentphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='currency',
            field=models.CharField(choices=[('uah', 'UAH'), ('dollar', '$'), ('euro', '€')], default='uah', max_length=10),
        ),
    ]
