# Generated by Django 5.0.6 on 2024-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_component_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('$', '$'), ('€', '€')], default='UAH', max_length=10),
        ),
    ]
