# Generated by Django 5.0.6 on 2024-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_component_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=20, verbose_name='Почта')),
                ('website', models.CharField(max_length=20, verbose_name='Сайт')),
            ],
        ),
    ]
