# Generated by Django 5.0.6 on 2024-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contacts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_1',
            field=models.CharField(max_length=14, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.CharField(max_length=30, verbose_name='Сайт'),
        ),
    ]
